from collections import namedtuple

DB2Feature = namedtuple('DB2Feature', [
    "dbCapacity",
    "dbVersion",
    "instanceName",
    "productName",
    "dbName",
    "serviceLevel",
    "instanceConn",
    "instanceUsedMem",
    "dbConn",
    "usedLog",
    "transcationInDoubt",
    "xlocksEscalation",
    "locksEscalation",
    "locksTimeOut",
    "deadLock",
    "lastBackupTime",
    "dbStatus",
    "instanceStatus",
    "bpIndexHitRatio",
    "bpDatahitRatio",
    "sortsInOverflow",
    "agetnsWait",
    "updateRows",
    "insertRows",
    "selectedRows",
    "deleteRows",
    "selects",
    "selectSQLs",
    "dynamicSQLs",
    "rollbacks",
    "commits",
    "bpTempIndexHitRatio",
    "bpTempDataHitRatio"
])
