FROM ubuntu:14.04


RUN apt-get update && \
    echo "y" | apt-get install python \
    python-dev \
    python-pip \
    build-essential \
    qemu-kvm \
  && pip install --upgrade pip 

WORKDIR /crawler
COPY crawler/requirements.txt /crawler/requirements.txt
COPY tests/requirements.txt /crawler/test-requirements.txt
 
RUN (pip install -r requirements.txt; pip install -r test-requirements.txt)

ADD . /crawler
RUN (pwd; ls -lt .; ls /proc/)

RUN (cd psvmi/psvmi; python setup.py build && python setup.py install)

COPY psvmi/maps maps
COPY psvmi/offsets offsets
COPY psvmi/header.h .

CMD (cd /crawler; python setup.py test --addopts '-s --cov=.')
