FROM ubuntu:14.04
WORKDIR /tmp/
RUN apt-get -y update && apt-get -y upgrade

# XXX might not need all of these packages
RUN apt-get install -y build-essential checkinstall \
	libreadline-gplv2-dev libncursesw5-dev libssl-dev libsqlite3-dev \
	tk-dev libgdbm-dev libc6-dev libbz2-dev \
	wget curl uuid netcat

RUN curl -fsSL https://get.docker.com/ | sh

ENV pyVer=2.7.5
RUN wget http://python.org/ftp/python/$pyVer/Python-${pyVer}.tgz && \
    tar -xvf Python-${pyVer}.tgz && \
	cd Python-${pyVer} && \
	./configure && \
	make && \
	checkinstall

RUN mkdir /crawler
COPY . /crawler/
WORKDIR /crawler/

RUN apt-get install -y python-dev python-pip
RUN pip install --upgrade pip
RUN pip install -r crawler/requirements.txt

# tests are pointing to this directory
RUN ln -s crawler config_and_metrics_crawler

WORKDIR tests
# let's pull an ubuntu image before starting the tests
CMD (docker daemon > ../docker.out 2>&1 &) && \
	sleep 5 && \
	docker pull ubuntu && \
	docker pull ubuntu:14.04 && \
	./test_all.sh
