FROM gliderlabs/alpine:3.3

RUN apk --no-cache add --repository http://dl-cdn.alpinelinux.org/alpine/edge/main libseccomp
RUN apk --no-cache add --repository http://dl-cdn.alpinelinux.org/alpine/edge/community docker

RUN apk add --update \
    python \
    python-dev \
    py-pip \
    build-base \
    linux-headers \
    docker \
  && rm -rf /var/cache/apk/*

WORKDIR /crawler

COPY . /crawler
RUN pip install -r crawler/requirements.txt
RUN pip install -r tests/requirements.txt

WORKDIR /crawler/tests
CMD (docker daemon > ../docker.out 2>&1 &) && \
	sleep 5 && \
	py.test 
