FROM alpine:3.3

RUN apk --no-cache add --repository http://dl-cdn.alpinelinux.org/alpine/edge/main libseccomp
RUN apk --no-cache add --repository http://dl-cdn.alpinelinux.org/alpine/edge/community docker

RUN apk add --update \
    python \
    python-dev \
    py-pip \
    build-base \
    linux-headers \
    docker \
  && pip install --upgrade pip \
  && rm -rf /var/cache/apk/*
 
COPY crawler/requirements.txt /requirements.txt
COPY tests/requirements.txt /requirements-test.txt
RUN pip install -r requirements.txt && pip install -r requirements-test.txt

WORKDIR /crawler

COPY . /crawler

CMD (docker daemon > ../docker.out 2>&1 &) && \
	sleep 5 && \
        flake8 --max-complexity 10 . || true && \
        pylint crawler || true && \
	py.test 
