The crawler is written in Python. It needs Python version 2.7.3 or higher. It is desinged to
be portable across Linux, Windows and AIX platforms. However, to date it has only been tested
on Linux platforms.

Run make to install all pre-reqs needed for the crawler:

	make

Look at README for instructions on how to run the crawler.

---------

You can optionally build a standalone crawler executable for deployment onto other machines
(that have glibc version >= that of the host on which you build the executable):

	make executable

this will create an executable binary called "crawler". You can then install just this executable
on other machines, and you will have a fully functioning crawler.

A useful way to deploy the crawler executable is to set it up as a service that is automatically
started at VM boot time (e.g. via init.d)

----------

You can optionally download a pre-built crawler executable for your platform from the crawler/binary directory
